PREFIX : <http://sibils.org/rdf#>
PREFIX sibils: <http://sibils.org/rdf/data/>
PREFIX sibilc: <http://sibils.org/rdf/concept/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT strlen(?word2)
  (str(?id) as ?id)
(substr(str(?sen),?pos+1, ?pos2-?pos +strlen(?word2)+1) as ?sentence )
  (str(?word)  as ?token)
  ?pos
  (str(?word2) as ?token2)
 (str(?cpt_id2) as ?cpt_id2)
 ?pos2
WHERE {
?publi :hasPubMedCentralId ?id.
  ?publi :hasAnnotation ?a .
  ?a :hasBody sibilc:MESH_D013987 .
  ?a :hasTarget ?trg .
  ?trg :hasSelector ?sel .
  ?sel :exact ?word.
  ?sel :start ?pos .
  ?trg :hasSource ?part.
?part :chars ?sen.

  ?publi :hasAnnotation ?a2 .
  ?a2 :hasTarget ?trg2.
  ?trg2 :hasSelector ?sel2 .
  ?sel2 :exact ?word2.
  ?sel2 :start ?pos2 .
  ?trg2 :hasSource ?part.
  ?a2 :hasBody ?cpt2.
  ?cpt2 :more_specific_than+ sibilc:NCIT_C26726 . # infectious disease
  ?cpt2 skos:notation ?cpt_id2.

 FILTER (?pos2 - ?pos < 30 && ?pos2 -?pos > 0 && ?a != ?a2)
}
